### ISSUE TITLE
HEAD fails to compile on 14.0-CURRENT after  c1472436b91a605ce6894947b890a1f948bd9804

### ISSUE THREAD

**Issue by dch** [freebsd/poudriere#924]
## Prerequisites

- [x] Have you checked for an existing issue describing your problem?
- [x] Are you running the latest version?
- [x] Is your ports tree recent?
- [ ] Is your FreeBSD Host on a [supported release](https://www.freebsd.org/security/#sup)? Nope Nope Nope

## Describe the bug

- 5ca4ed748084c10d69f4073c0504a5444e0cf580
- builds fine on amd64 13.0-RELEASE
- fails on 14.0-CURRENT arm64
- build succeeds when this is reverted (not saying poudriere works, just it compiles now)

```
  CC       src/libexec/poudriere/pwait/sh-pwait.o
src/libexec/poudriere/pwait/pwait.c:62:2: error: passing 'void *' to parameter of incompatible type 'va_list' (aka '__builtin_va_list')
        exit(EX_USAGE);
        ^~~~~~~~~~~~~~
./src/poudriere-sh/helpers.h:106:20: note: expanded from macro 'exit'
#define exit(...)               exit_(_, ##__VA_ARGS__)
                                ^~~~~~~~~~~~~~~~~~~~~~~
./src/poudriere-sh/helpers.h:107:21: note: expanded from macro 'exit_'
#define exit_(...)              exit_X(__VA_ARGS__, _1, _0)(__VA_ARGS__)
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./src/poudriere-sh/helpers.h:108:32: note: expanded from macro 'exit_X'
#define exit_X(_0, _1, X, ...)  exit ## X
                                ^
<scratch space>:43:1: note: expanded from here
exit_1
...
```

## How to reproduce

1. git clone as usual
2. `git clean -fdxx && ./configure && make`

## Expected behavior

- build succeeds

## Environment

 - Host OS: 14.0-CURRENT main-n249551-00582fa6605
 - Poudriere Version: 5ca4ed748084c10d69f4073c0504a5444e0cf580 (includes bad commit)

### git bisect log

```
$ git bisect start
# good: [44944df7f40e7ef332b505d3e4dad567047e2a61] Package Fetch: Clarify cached packages may be used.
git bisect good 44944df7f40e7ef332b505d3e4dad567047e2a61
# bad: [3840e05f5f60b6ea6466cc22811a3be7e52bbecd] [PATCH] Fix booting ZFS images.
git bisect bad 3840e05f5f60b6ea6466cc22811a3be7e52bbecd
# good: [09da2a0f8014c2b61a290d94d35e23fc7041ea0f] distclean: Cleanup __MAKE_CONF after every -p iteration.
git bisect good 09da2a0f8014c2b61a290d94d35e23fc7041ea0f
# good: [6d3fe23c9e43b9469536f330ede5c0015fd9c89f] pkgqueue_remaining: Unhide errors
git bisect good 6d3fe23c9e43b9469536f330ede5c0015fd9c89f
# bad: [c1472436b91a605ce6894947b890a1f948bd9804] sh: Fix exit(0) to do a return
git bisect bad c1472436b91a605ce6894947b890a1f948bd9804
# good: [eff0a5468dda3b01c8fa63685a6ebb010cfbcbf3] delete_all_pkgs: Need to lookup cache_dir.
git bisect good eff0a5468dda3b01c8fa63685a6ebb010cfbcbf3
# good: [5d607a5c52f67407eeccc81a135536c40ecec601] pkg_get*: SHASH_VAR_PREFIX should always be empty here
git bisect good 5d607a5c52f67407eeccc81a135536c40ecec601
# good: [ba263e1580300d64a9997995ba44daaf72973b2b] required_env: Properly detect the not blank nor null case
git bisect good ba263e1580300d64a9997995ba44daaf72973b2b
# first bad commit: [c1472436b91a605ce6894947b890a1f948bd9804] sh: Fix exit(0) to do a return
```

**Comment by bdrewery** [comment]
Fixed by 0070a55f9c
